@host = https://localhost
@port = 7142
@Restaurants.API_HostAddress = https://localhost:7142
@token = CfDJ8JvfsLB7ptBBg_-VsQaBR_6qwF_YoVUxAp74ldcXEGXx4SH8i6wGm7deUQH-7WxU5kEVESKw5-xgW__jOStuuC4xMxWOGOc37kccr2-04XUkphIA14fnelF6A8IjTKuAjW9utUATonx0oYnYqLRAqJPZtY7gWnI33iAc0mTDSgTAp5WEB3zc3UgNz8jAXwfyuTX7hiIShOjTPYeE4Xae7LhjoD_IAmCqVldMq2NBQvMf0zrfsIVxnv5syLQ5pbj8pkhTOadKxxRvfapeihpkV_MTdSFQDbj5W4LfxGu2Pt7mVfap79fFUhH9caTenHOfT23NWxMjmY6b9dCEgVs90C-rB5yhan_aq5HANZ4x7usvYlCXvuULuevfPYBE4F4l01lIkM-5a5L5amkG2m8xkT85R0iR87OMfiARJPbfYh-f9iJSlt6iTUootDXGPflt1caXlq79yKANQHXCcqnlLl9tObsZSGtJqcx5UfoFZ_vzJljls2tg2Lx3iNSaoS6FJClqs4POtc1L2PJ-WjGcWV5ZaJd-OnVixUsyBDdnNV7hvgAarpNOOb5l72LeUyIFmrthh9aQ4hy01CCyYJLNU3aSZkd8ecyNGKGpTYVb1km3azMuXK0yH7f_ZUDWwvHzjpnY-4d1mMN30GWzB-Kv9x6j0awEkPXQqULXHBG4MGHFquPsIi21c1TxqoFSpb3WAeXni3rdTgl6t_jrgtBCVbwg-jSAtyo-Q3b5-y5orBK30QLugQyMEDNivxyd-9jSaBczZ3aG4AlJknthZc6exZOrpmffOPzv5W-qAuFpVKTh

GET {{Restaurants.API_HostAddress}}/api/restaurants?searchPhrase=&pageSize=10&pageNumber=1&sortBy=Name&sortDirection=Descending
Content-Type: application/json
Authorization: Bearer {{token}}

###
GET {{Restaurants.API_HostAddress}}/api/restaurants/1
Content-Type: application/json
Authorization: Bearer {{token}}
###

POST {{Restaurants.API_HostAddress}}/api/restaurants
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "Name": "Spicy Delights",
  "Description": "A culinary experience like no other",
  "Category": "Indian",
  "HasDelivery": true,
  "COntactEmail": "info@gourmetdelights.com",
  "ContactNumber": "555-123-4567",
  "City": "Metropolis",
  "Street": "456 Gourmet Avenue",
  "PostalCode": "54-321"
}

###
DELETE {{Restaurants.API_HostAddress}}/api/restaurants/2
Content-Type: application/json
###

PATCH {{Restaurants.API_HostAddress}}/api/restaurants/3
Content-Type: application/json

{
  "Name": "Spicy Delights for restaurant3",
  "Description": "A culinary experience like no other for restaurant 3",
  "HasDelivery": true
}

###

POST {{Restaurants.API_HostAddress}}/api/restaurants/3/dishes
Content-Type: application/json

{
  "Name": "Spaghetti Bolognese for new testing",
  "Description": "Classic Italian paste dish with rich meat sauce for new testing",
  "Price": 12.99,
  "KiloCalories": 750
}

###


GET {{Restaurants.API_HostAddress}}/api/restaurants/3/dishes/5

###

DELETE {{Restaurants.API_HostAddress}}/api/restaurants/3/dishes

###

DELETE {{Restaurants.API_HostAddress}}/api/restaurants/3/dishes/6

###

POST {{Restaurants.API_HostAddress}}/api/identity/register
Content-Type: application/json

{
  "email": "owner@test.com",
  "password": "Password1#"
}

###
POST {{Restaurants.API_HostAddress}}/api/identity/login
Content-Type: application/json

{
  "email": "owner@test.com",
  "password": "Password1#"
}