@host = https://localhost
@port = 7142
@Restaurants.API_HostAddress = https://localhost:7142

GET {{Restaurants.API_HostAddress}}/api/restaurants
Content-Type: application/json

###
GET {{Restaurants.API_HostAddress}}/api/restaurants/3
Content-Type: application/json
###

POST {{Restaurants.API_HostAddress}}/api/restaurants
Content-Type: application/json

{
  "Name": "Spicy Delights2",
  "Description": "A culinary experience like no other2",
  "Category": "Indian",
  "HasDelivery": true,
  "COntactEmail": "info@gourmetdelights.com",
  "ContactNumber": "555-123-4567",
  "City": "Metropolis",
  "Street": "456 Gourmet Avenue",
  "PostalCode": "54-321"
}

###
DELETE {{Restaurants.API_HostAddress}}/api/restaurants/2
Content-Type: application/json
###

PATCH {{Restaurants.API_HostAddress}}/api/restaurants/3
Content-Type: application/json

{
  "Name": "Spicy Delights for restaurant3",
  "Description": "A culinary experience like no other for restaurant 3",
  "HasDelivery": true
}

###

POST {{Restaurants.API_HostAddress}}/api/restaurants/3/dishes
Content-Type: application/json

{
  "Name": "Spaghetti Bolognese for new testing",
  "Description": "Classic Italian paste dish with rich meat sauce for new testing",
  "Price": 12.99,
  "KiloCalories": 750
}

###


GET {{Restaurants.API_HostAddress}}/api/restaurants/3/dishes/5

###

DELETE {{Restaurants.API_HostAddress}}/api/restaurants/3/dishes

###

DELETE {{Restaurants.API_HostAddress}}/api/restaurants/3/dishes/6

###
